create database grocery_store;
use grocery_store;

CREATE TABLE supplier (
    sup_id TINYINT AUTO_INCREMENT PRIMARY KEY,
    sup_name VARCHAR(255),
    address TEXT
);

CREATE TABLE categories (
    cat_id TINYINT AUTO_INCREMENT PRIMARY KEY,
    cat_name VARCHAR(255)
);

CREATE TABLE employees (
    emp_id TINYINT AUTO_INCREMENT PRIMARY KEY,
    emp_name VARCHAR(255),
    hire_date VARCHAR(255)
);

CREATE TABLE customers (
    cust_id SMALLINT AUTO_INCREMENT PRIMARY KEY,
    cust_name VARCHAR(255),
    address TEXT
);

CREATE TABLE products (
    prod_id TINYINT AUTO_INCREMENT PRIMARY KEY,
    prod_name VARCHAR(255),
    sup_id TINYINT,
    cat_id TINYINT,
    price DECIMAL(10,2),
    FOREIGN KEY (sup_id) REFERENCES supplier(sup_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (cat_id) REFERENCES categories(cat_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE orders (
    ord_id SMALLINT AUTO_INCREMENT PRIMARY KEY,
    cust_id SMALLINT,
    emp_id TINYINT,
    order_date VARCHAR(255),
    FOREIGN KEY (cust_id) REFERENCES customers(cust_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (emp_id) REFERENCES employees(emp_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE order_details (
    ord_detID SMALLINT AUTO_INCREMENT PRIMARY KEY,
    ord_id SMALLINT,
    prod_id TINYINT,
    quantity TINYINT,
    each_price DECIMAL(10,2),
    total_price DECIMAL(10,2),
    FOREIGN KEY (ord_id) REFERENCES orders(ord_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (prod_id) REFERENCES products(prod_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

SELECT * FROM supplier;
select * from categories;
select * from employees;
select * from customers;
select * from products;
select * from orders;
select * from order_details;


-- Analysis Questions
-- 1️. Customer Insights
-- Gain an understanding of customer engagement and purchasing behavior.
-- How many unique customers have placed orders?
select count(distinct cust_id) as unique_customers from orders;

-- Which customers have placed the highest number of orders?
select cust_id, max(ord_id) from orders
group by cust_id
order by max(ord_id) desc;

select cust_id, count(*) as max from orders
group by cust_id
order by max desc;

-- What is the total and average purchase value per customer?
select o. cust_id, sum(od.total_price) as total_purchase_value, 
avg(od.total_price) as average_purchase_value 
from order_details as od
join orders as o
on od.ord_id=o.ord_id
group by o.cust_id;

select o. cust_id, sum(od.total_price) as total_purchase_value, 
avg(od.total_price) as average_purchase_value 
from orders as o
join order_details as od
on o.ord_id=od.ord_id
group by o.cust_id;
-- Who are the top 5 customers by total purchase amount?
select o.cust_id , sum(od.total_price) as total_purchase_amount
from orders as o
join order_details as od
group by o.cust_id
order by total_purchase_amount desc
limit 5;
-- 2. Product Performance
-- Evaluate how well products are performing in terms of sales and revenue.
-- How many products exist in each category?
select c.cat_id,count(p.prod_id) from categories as c
join products as p
on c.cat_id=p.cat_id
group by c.cat_id;

SELECT cat_id, COUNT(*) AS product_count FROM products GROUP BY cat_id;


-- What is the average price of products by category?
select cat_id, avg(price) as average_price from products
group by cat_id;

-- Which products have the highest total sales volume (by quantity)?
select prod_id, sum(quantity) as total_sales_volume from order_details
group by prod_id
order by total_sales_volume desc;

-- What is the total revenue generated by each product?
select prod_id, sum(total_price) as total_revenue from order_details
group by prod_id;

-- How do product sales vary by category and supplier?
select prod_id, sup_id, cat_id from products;
-- 3. Sales and Order Trends
-- Analyze business performance through orders and revenue over time.
-- How many orders have been placed in total?
select  count(*) from orders;

-- What is the average value per order?
SELECT AVG(order_total) AS avg_order_value
FROM (
  SELECT ord_id, SUM(total_price) AS order_total
  FROM order_details
  GROUP BY ord_id
) AS sub;


-- On which dates were the most orders placed?
SELECT order_date, COUNT(*) AS order_count
FROM orders
GROUP BY order_date
ORDER BY order_count DESC;



-- What are the monthly trends in order volume and revenue?
SELECT LEFT(order_date, 7) AS month, COUNT(*) AS order_count, SUM(od.total_price) AS revenue
FROM orders o
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY month
ORDER BY month;

-- How do order patterns vary across weekdays and weekends?
SELECT 
  CASE 
    WHEN DAYOFWEEK(STR_TO_DATE(order_date, '%m-%d-%Y')) IN (1, 7) THEN 'Weekend'
    ELSE 'Weekday'
  END AS day_type,
  COUNT(*) AS order_count
FROM orders
GROUP BY day_type;



-- 4️. Supplier Contribution
-- Identify the most active and profitable suppliers.
-- How many suppliers are there in the database?
select count(*) from supplier; 

-- Which supplier provides the most products?
SELECT s.sup_name, COUNT(*) AS product_count
FROM supplier s
JOIN products p 
ON s.sup_id = p.sup_id
GROUP BY s.sup_id
ORDER BY product_count DESC;

-- What is the average price of products from each supplier?
select s.sup_name, avg(p.price) as average_price from supplier as s
join products p
on s.sup_id=p.sup_id
group by s.sup_id;

-- Which suppliers contribute the most to total product sales (by revenue)?
SELECT s.sup_name, sum(od.total_price) AS total_revenue
FROM supplier s
JOIN products p ON s.sup_id = p.sup_id
join order_details od on p.prod_id= od.prod_id
GROUP BY s.sup_id
order by total_revenue desc;

-- 5️. Employee Performance
-- Assess how employees are handling and influencing sales.
-- How many employees have processed orders?
select count(distinct emp_id) as Total_employess from orders;

-- Which employees have handled the most orders?
select e.emp_name, count(*) as total_orders from employees as e
join orders as o
on e.emp_id=o.emp_id
group by e.emp_id
order by total_orders;

-- What is the total sales value processed by each employee?
select e.emp_name, sum(od.total_price) as Total_sales from employees as e
join orders as o
on e.emp_id=o.emp_id
join order_details as od
on o.ord_id=od.ord_id
group by e.emp_id;

-- What is the average order value handled per employee?
 SELECT e.emp_name, AVG(order_total) AS avg_order_value
FROM employees e
JOIN (
  SELECT o.emp_id, o.ord_id, SUM(od.total_price) AS order_total
  FROM orders o
  JOIN order_details od ON o.ord_id = od.ord_id
  GROUP BY o.ord_id
) AS sub ON e.emp_id = sub.emp_id
GROUP BY e.emp_id;

-- 6️. Order Details Deep Dive
-- Explore item-level sales patterns and pricing behavior.
-- What is the relationship between quantity ordered and total price?
select quantity, avg(total_price) as avg_total
from order_details
group by quantity;

-- What is the average quantity ordered per product?
select p.prod_name, avg(od.quantity) as avg_quantity from products as p
join order_details as od
on p.prod_id=od.prod_id
group by p.prod_id;



-- How does the unit price vary across products and orders?
select p.prod_name, avg(od.each_price) as avg_unit_price from products as p
join order_details as od
on p.prod_id=od.prod_id
group by p.prod_id;